env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
#включает поддержку конструкции import.meta.url
rules:
  import/extensions: #
    - error
    - ignorePackages
    - js: always
  no-console: off #убирает ошибку вывода в консоль (console.log)
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
